development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  username: username
  password: password

production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  username: username
  password: password