# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc50ee7e4fb379c29ba811ac080869ef3b43856a6a7fb2b30c512946a344914d78fad1595538d12576951823e1e83404d5acfa59fea6fc50a8ddb38f4d884861
  flight_data:
    google_api_key: AIzaSyAMXNJ-bCk0_vUmru_jggyoawl0Vo_1ZL0
    project_name: flight_system
    project_token: 1df9ffe5-2bba-4015-af77-013715902f65
    google_api: GoogleFlightsAPI
    trip_type: searchSingleTrip

test:
  secret_key_base: b5e0f4fef540bf424c3954c88f9d21750235e5ff5ed043fa826f786b7db8c359946c9f531ee012373e239bf15d5e30210812ac83533f7540b1bdb8d204a993b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  flight_data:
    google_api_key: AIzaSyAMXNJ-bCk0_vUmru_jggyoawl0Vo_1ZL0
    project_name: flight_system
    project_token: 1df9ffe5-2bba-4015-af77-013715902f65
    google_api: GoogleFlightsAPI
    trip_type: searchSingleTrip